### ISSUE TITLE
مشکل در جواب

### ISSUE THREAD

**Issue by mreza0100** [mrbardia72/Go-Interview-Questions-And-Answers#6]
[سوال](https://github.com/mrbardia72/Go-Interview-Questions-And-Answers#--%DA%86%D9%87-%D9%85%D9%88%D9%82%D8%B9%DB%8C-%D8%A7%D8%B2-channel-%D9%88-%DA%86%D9%87-%D9%85%D9%88%D9%82%D8%B9%DB%8C-%D8%A7%D8%B2-mutex-%D8%A7%D8%B3%D8%AA%D9%81%D8%A7%D8%AF%D9%87-%D9%85%DB%8C%D8%B4%D9%87-%D8%A8%D8%B1%D8%A7%DB%8C-%DA%AF%D9%88%D8%B1%D8%AA%DB%8C%D9%86%DA%AF-%D9%87%D8%A7%D8%A8%D8%AD%D8%AB-%D8%A7%D8%B1%D8%AA%D8%A8%D8%A7%D8%B7-)

جواب حال حاضر: درصورتی که فقط یک Goroutine دارید و باید به بخش مهم کد دسترسی داشته باشد از Mutexes استفاده کنید.
مشکل: وقتی از Mutexes استفاده میکنیم که چندین چنل میخواهند به یک قسمت از حافظه دسترسی داشته باشند و از Mutexes برای لاک کردن استفاده میکنیم، نه برای دسترسی به قسمت مهم حافظه
این کار جهت جلوگیری از race condition انجام میشود
در هر data structure و برای هر نوع عملیات(read/write) متفاوت است.

[Race condition example](https://stackoverflow.com/questions/53328571/most-simple-go-race-condition-example)
[Mutexes](https://gobyexample.com/mutexes)

**Comment by mrbardia72** [comment]
اینجا هم بهش اشاره شده در سوال پایین
seedling فرق Atomic و mutex؟
