### ISSUE TITLE
تفاوت array و slice چیست؟

### ISSUE THREAD

**Issue by masihtehrani** [mrbardia72/Go-Interview-Questions-And-Answers#7]

**Comment by mrbardia72** [comment]
Golang array:
is fixed-size (OK, nothing weird here);
has a type (sure, all Go variables are strictly typed), and we only can have one type per array (e.g. array of strings, array of integers and so on);
it’s length is a type as well (uuhhm.. just remember [3]int is distinct from [4]int and you’ll be fine);
consist of contiguous memory locations (so the in-memory representation of [4]int is just four integer values laid out sequentially, got it);
array variable is not a pointer to the first array element, array variable stands for the whole array;
---------------
Slice consists of:
a pointer to the array (yay, finally a pointer!), or actually pointer wrapper struct value, but let’s not go deeper there, pointer on it’s own is alright;
the length of the segment (e.g. meaning elements 0:5 of the array)
slice capacity (maximum length it can store)
